create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_id text not null unique,
  email text not null,
  amount numeric not null,
  status text not null default 'created',
  cf_payment_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.buyers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  full_name text,
  phone text,
  has_access boolean not null default false,
  role text not null default 'buyer',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.buyers add column if not exists full_name text;
alter table public.buyers add column if not exists phone text;

create index if not exists orders_email_idx on public.orders (email);
create index if not exists buyers_email_idx on public.buyers (email);
